[package]
name = "bevy-midi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
bevy_egui = "0.20.2"
chrono = "0.4.24"
crossbeam-channel = "0.5.8"
midir = "0.9.1"
